### PR TITLE
chore: add golangci-lint configuration

### PR DESCRIPTION
**Pull request by enocom**

### CODE REVIEW

**Comment by enocom** [comment]
Here's what golangci-lint looks like. I've purposely left the build failing to show what errors appear as.

We'll start by making this an optional build step and after some tuning will make it required.

**Comment by kurtisvg** [comment]
Does this replace our current lint flow? (or should it just be added to it?)

**Comment by enocom** [comment]
The new linter will catch files that not have been gofmt'd with gorimports. See [here](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/actions/runs/3176323054/jobs/5175485517).

**Comment by enocom** [comment]
This will mostly extend our existing lint setup. Checking `go mod tidy` is still required, but golangci-lint will check goimports for us.

**Review by hessjcg — APPROVED** [review]
LGTM

**Pull request merged**
